cms:
    page_elements:
        Image:
            class: RevisionTen\CmsElements\Elements\BetterDefault\Image
            template: '@CmsElements/BetterDefault/image.html.twig'
            public: true
            icon: 'fa fa-image'
            styles:
                align image center: 'text-center'
                align image right: 'text-right'
