cms:
    page_elements:
        Images:
            class: RevisionTen\CmsElements\Elements\BetterDefault\Images
            template: 'CmsElementsBundle:BetterDefault:images.html.twig'
            public: true
            icon: 'fa fa-images'
