cms:
    page_elements:
        VehicleOffer:
            class: RevisionTen\CmsElements\Elements\Vehicle\VehicleOffer
            template: '@CmsElements/Vehicle/offer.html.twig'
            icon: 'fa fa-car'
            public: true
            type: 'Section'
            children:
                - 'Row'
                - 'VehicleWLTP'
                - 'VehicleFinancing'
                - 'VehicleDatDisclaimer'
        VehicleEnVKV:
            class: RevisionTen\CmsElements\Elements\Vehicle\VehicleEnVKV
            template: '@CmsElements/Vehicle/envkv.html.twig'
            icon: 'fa fa-leaf'
            public: false
        VehicleWLTP:
            class: RevisionTen\CmsElements\Elements\Vehicle\VehicleWLTP
            template: '@CmsElements/Vehicle/wltp.html.twig'
            icon: 'fa fa-leaf'
            public: false
        VehicleFinancing:
            class: RevisionTen\CmsElements\Elements\Vehicle\VehicleFinancing
            template: '@CmsElements/Vehicle/financing.html.twig'
            icon: 'fa fa-euro-sign'
            public: true
        VehicleDatDisclaimer:
            class: RevisionTen\CmsElements\Elements\Vehicle\VehicleDatDisclaimer
            template: '@CmsElements/Vehicle/dat_disclaimer.html.twig'
            icon: 'fa fa-exclamation-triangle'
            public: true

services:
    RevisionTen\CmsElements\Elements\Vehicle\EcoData:
        autowire: true
        public: true
twig:
    globals:
        ecodata_service: '@RevisionTen\CmsElements\Elements\Vehicle\EcoData'

